name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rayriffy
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: buildx
        uses: docker/setup-buildx-action@v2
      - name: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/rayriffy/api-runtime
      - name: deploy
        uses: deploys-app/deploys-action@v1
        with:
          project: rayriffy
          location: gke.cluster-rcf2
          name: api
          image: ghcr.io/rayriffy/api-runtime
          minReplicas: 1
          maxReplicas: 4
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
